def get_board():
    list_board = [{'name': 'go',
                   'type': 'go'},
                  {'name': 'old kent road',
                   'type': 'road'},
                  {'name': 'community chest',
                   'type': 'community chest'},
                  {'name': 'whitechapel road',
                   'type': 'road'},
                  {'name': 'income tax',
                   'type': 'tax'},
                  {'name': 'kings cross station',
                   'type': 'station'},
                  {'name': 'the angel islington',
                   'type': 'road'},
                  {'name': 'chance',
                   'type': 'chance'},
                  {'name': 'euston road',
                   'type': 'road'},
                  {'name': 'pentonville road',
                   'type': 'road'},
                  {'name': 'jail',
                   'type': 'jail'},
                  {'name': 'pall mall',
                   'type': 'road'},
                  {'name': 'Electric company',
                   'type': 'utility'},
                  {'name': 'whitehall',
                   'type': 'road'},
                  {'name': 'northumberland avenue',
                   'type': 'road'},
                  {'name': 'marylebone station',
                   'type': 'station'},
                  {'name': 'bow street',
                   'type': 'road'},
                  {'name': 'community chest',
                   'type': 'community chest'},
                  {'name': 'marlborough street',
                   'type': 'road'},
                  {'name': 'vine street',
                   'type': 'road'},
                  {'name': 'free parking',
                   'type': 'free parking'},
                  {'name': 'strand',
                   'type': 'road'},
                  {'name': 'chance',
                   'type': 'chance'},
                  {'name': 'fleet street',
                   'type': 'road'},
                  {'name': 'trafalgar square',
                   'type': 'road'},
                  {'name': 'Fenchurch st. station',
                   'type': 'station'},
                  {'name': 'leicester square',
                   'type': 'road'},
                  {'name': 'coventry street',
                   'type': 'road'},
                  {'name': 'water works',
                   'type': 'utility'},
                  {'name': 'piccadilly',
                   'type': 'road'},
                  {'name': 'go to jail',
                   'type': 'go to jail'},
                  {'name': 'regent street',
                   'type': 'road'},
                  {'name': 'oxford street',
                   'type': 'road'},
                  {'name': 'community chest',
                   'type': 'community chest'},
                  {'name': 'bond street',
                   'type': 'road'},
                  {'name': 'liverpool st station',
                   'type': 'station'},
                  {'name': 'chance',
                   'type': 'chance'},
                  {'name': 'park lane',
                   'type': 'road'},
                  {'name': 'super tax',
                   'type': 'tax'},
                  {'name': 'mayfair',
                   'type': 'road'}
                  ]
    return list_board


def get_bank():

    dict_bank = {'cash': 5000,
                 'houses': 32,
                 'hotels': 12}
    return dict_bank


def get_roads():

    dict_roads = {
        'old kent road': {
            'name': 'old kent road',
            'type': 'road',
            'price': 60,
            'rent': 2,
            'rent_with_color_set': 4,
            'rent_with_1_houses_0_hotels': 10,
            'rent_with_2_houses_0_hotels': 30,
            'rent_with_3_houses_0_hotels': 90,
            'rent_with_4_houses_0_hotels': 160,
            'rent_with_4_houses_1_hotels': 250,
            'mortgage_value': 30,
            'unmortgage_value': 33,
            'houses_cost': 50,
            'hotels_cost': 50,
            'color': 'brown',
            'board_num': 1,
            'belongs_to': None,
            'is_mortgaged': False},
        'whitechapel road': {
            'name': 'whitechapel road',
            'type': 'road',
            'price': 60,
            'rent': 4,
            'rent_with_color_set': 8,
            'rent_with_1_houses_0_hotels': 20,
            'rent_with_2_houses_0_hotels': 60,
            'rent_with_3_houses_0_hotels': 180,
            'rent_with_4_houses_0_hotels': 320,
            'rent_with_4_houses_1_hotels': 450,
            'mortgage_value': 30,
            'unmortgage_value': 33,
            'houses_cost': 50,
            'hotels_cost': 50,
            'color': 'brown',
            'board_num': 3,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'the angel islington': {
            'name': 'the angel islington',
            'type': 'road',
            'price': 100,
            'rent': 6,
            'rent_with_color_set': 12,
            'rent_with_1_houses_0_hotels': 30,
            'rent_with_2_houses_0_hotels': 90,
            'rent_with_3_houses_0_hotels': 270,
            'rent_with_4_houses_0_hotels': 400,
            'rent_with_4_houses_1_hotels': 550,
            'mortgage_value': 50,
            'unmortgage_value': 55,
            'houses_cost': 50,
            'hotels_cost': 50,
            'color': 'light_blue',
            'board_num': 6,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'euston road': {
            'name': 'euston road',
            'type': 'road',
            'price': 100,
            'rent': 6,
            'rent_with_color_set': 12,
            'rent_with_1_houses_0_hotels': 30,
            'rent_with_2_houses_0_hotels': 90,
            'rent_with_3_houses_0_hotels': 270,
            'rent_with_4_houses_0_hotels': 400,
            'rent_with_4_houses_1_hotels': 550,
            'mortgage_value': 50,
            'unmortgage_value': 55,
            'houses_cost': 50,
            'hotels_cost': 50,
            'color': 'light_blue',
            'board_num': 8,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'pentonville road': {
            'name': 'pentonville road',
            'type': 'road',
            'price': 120,
            'rent': 8,
            'rent_with_color_set': 16,
            'rent_with_1_houses_0_hotels': 40,
            'rent_with_2_houses_0_hotels': 100,
            'rent_with_3_houses_0_hotels': 300,
            'rent_with_4_houses_0_hotels': 450,
            'rent_with_4_houses_1_hotels': 600,
            'mortgage_value': 60,
            'unmortgage_value': 66,
            'houses_cost': 50,
            'hotels_cost': 50,
            'color': 'light_blue',
            'board_num': 9,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'pall mall': {
            'name': 'pall mall',
            'type': 'road',
            'price': 140,
            'rent': 10,
            'rent_with_color_set': 20,
            'rent_with_1_houses_0_hotels': 50,
            'rent_with_2_houses_0_hotels': 150,
            'rent_with_3_houses_0_hotels': 450,
            'rent_with_4_houses_0_hotels': 625,
            'rent_with_4_houses_1_hotels': 750,
            'mortgage_value': 70,
            'unmortgage_value': 77,
            'houses_cost': 100,
            'hotels_cost': 100,
            'color': 'purple',
            'board_num': 11,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'whitehall': {
            'name': 'whitehall',
            'type': 'road',
            'price': 140,
            'rent': 10,
            'rent_with_color_set': 20,
            'rent_with_1_houses_0_hotels': 50,
            'rent_with_2_houses_0_hotels': 150,
            'rent_with_3_houses_0_hotels': 450,
            'rent_with_4_houses_0_hotels': 625,
            'rent_with_4_houses_1_hotels': 750,
            'mortgage_value': 70,
            'unmortgage_value': 77,
            'houses_cost': 100,
            'hotels_cost': 100,
            'color': 'purple',
            'board_num': 13,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'northumberland avenue': {
            'name': 'northumberland avenue',
            'type': 'road',
            'price': 160,
            'rent': 12,
            'rent_with_color_set': 24,
            'rent_with_1_houses_0_hotels': 60,
            'rent_with_2_houses_0_hotels': 180,
            'rent_with_3_houses_0_hotels': 500,
            'rent_with_4_houses_0_hotels': 700,
            'rent_with_4_houses_1_hotels': 900,
            'mortgage_value': 80,
            'unmortgage_value': 88,
            'houses_cost': 100,
            'hotels_cost': 100,
            'color': 'purple',
            'board_num': 14,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'bow street': {
            'name': 'bow street',
            'type': 'road',
            'price': 180,
            'rent': 14,
            'rent_with_color_set': 28,
            'rent_with_1_houses_0_hotels': 70,
            'rent_with_2_houses_0_hotels': 200,
            'rent_with_3_houses_0_hotels': 550,
            'rent_with_4_houses_0_hotels': 750,
            'rent_with_4_houses_1_hotels': 950,
            'mortgage_value': 90,
            'unmortgage_value': 99,
            'houses_cost': 100,
            'hotels_cost': 100,
            'color': 'orange',
            'board_num': 16,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'marlborough street': {
            'name': 'marlborough street',
            'type': 'road',
            'price': 180,
            'rent': 14,
            'rent_with_color_set': 28,
            'rent_with_1_houses_0_hotels': 70,
            'rent_with_2_houses_0_hotels': 200,
            'rent_with_3_houses_0_hotels': 550,
            'rent_with_4_houses_0_hotels': 750,
            'rent_with_4_houses_1_hotels': 950,
            'mortgage_value': 90,
            'unmortgage_value': 99,
            'houses_cost': 100,
            'hotels_cost': 100,
            'color': 'orange',
            'board_num': 18,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'vine street': {
            'name': 'vine street',
            'type': 'road',
            'price': 200,
            'rent': 16,
            'rent_with_color_set': 32,
            'rent_with_1_houses_0_hotels': 80,
            'rent_with_2_houses_0_hotels': 220,
            'rent_with_3_houses_0_hotels': 600,
            'rent_with_4_houses_0_hotels': 800,
            'rent_with_4_houses_1_hotels': 1000,
            'mortgage_value': 100,
            'unmortgage_value': 110,
            'houses_cost': 100,
            'hotels_cost': 100,
            'color': 'orange',
            'board_num': 19,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'strand': {
            'name': 'strand',
            'type': 'road',
            'price': 220,
            'rent': 18,
            'rent_with_color_set': 36,
            'rent_with_1_houses_0_hotels': 90,
            'rent_with_2_houses_0_hotels': 250,
            'rent_with_3_houses_0_hotels': 700,
            'rent_with_4_houses_0_hotels': 875,
            'rent_with_4_houses_1_hotels': 1050,
            'mortgage_value': 110,
            'unmortgage_value': 121,
            'houses_cost': 150,
            'hotels_cost': 150,
            'color': 'red',
            'board_num': 21,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'fleet street': {
            'name': 'fleet street',
            'type': 'road',
            'price': 220,
            'rent': 18,
            'rent_with_color_set': 36,
            'rent_with_1_houses_0_hotels': 90,
            'rent_with_2_houses_0_hotels': 250,
            'rent_with_3_houses_0_hotels': 700,
            'rent_with_4_houses_0_hotels': 875,
            'rent_with_4_houses_1_hotels': 1050,
            'mortgage_value': 110,
            'unmortgage_value': 121,
            'houses_cost': 150,
            'hotels_cost': 150,
            'color': 'red',
            'board_num': 23,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'trafalgar square': {
            'name': 'trafalgar square',
            'type': 'road',
            'price': 240,
            'rent': 20,
            'rent_with_color_set': 40,
            'rent_with_1_houses_0_hotels': 100,
            'rent_with_2_houses_0_hotels': 300,
            'rent_with_3_houses_0_hotels': 750,
            'rent_with_4_houses_0_hotels': 925,
            'rent_with_4_houses_1_hotels': 1100,
            'mortgage_value': 120,
            'unmortgage_value': 132,
            'houses_cost': 150,
            'hotels_cost': 150,
            'color': 'red',
            'board_num': 24,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'leicester square': {
            'name': 'leicester square',
            'type': 'road',
            'price': 260,
            'rent': 22,
            'rent_with_color_set': 44,
            'rent_with_1_houses_0_hotels': 110,
            'rent_with_2_houses_0_hotels': 330,
            'rent_with_3_houses_0_hotels': 800,
            'rent_with_4_houses_0_hotels': 975,
            'rent_with_4_houses_1_hotels': 1150,
            'mortgage_value': 130,
            'unmortgage_value': 143,
            'houses_cost': 150,
            'hotels_cost': 150,
            'color': 'yellow',
            'board_num': 26,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'coventry street': {
            'name': 'coventry street',
            'type': 'road',
            'price': 260,
            'rent': 22,
            'rent_with_color_set': 44,
            'rent_with_1_houses_0_hotels': 110,
            'rent_with_2_houses_0_hotels': 330,
            'rent_with_3_houses_0_hotels': 800,
            'rent_with_4_houses_0_hotels': 975,
            'rent_with_4_houses_1_hotels': 1150,
            'mortgage_value': 130,
            'unmortgage_value': 143,
            'houses_cost': 150,
            'hotels_cost': 150,
            'color': 'yellow',
            'board_num': 27,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'piccadilly': {
            'name': 'piccadilly',
            'type': 'road',
            'price': 280,
            'rent': 24,
            'rent_with_color_set': 48,
            'rent_with_1_houses_0_hotels': 120,
            'rent_with_2_houses_0_hotels': 360,
            'rent_with_3_houses_0_hotels': 850,
            'rent_with_4_houses_0_hotels': 1025,
            'rent_with_4_houses_1_hotels': 1200,
            'mortgage_value': 140,
            'unmortgage_value': 154,
            'houses_cost': 150,
            'hotels_cost': 150,
            'color': 'yellow',
            'board_num': 29,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'regent street': {
            'name': 'regent street',
            'type': 'road',
            'price': 300,
            'rent': 26,
            'rent_with_color_set': 52,
            'rent_with_1_houses_0_hotels': 130,
            'rent_with_2_houses_0_hotels': 390,
            'rent_with_3_houses_0_hotels': 900,
            'rent_with_4_houses_0_hotels': 1100,
            'rent_with_4_houses_1_hotels': 1275,
            'mortgage_value': 150,
            'unmortgage_value': 165,
            'houses_cost': 200,
            'hotels_cost': 200,
            'color': 'green',
            'board_num': 31,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'oxford street': {
            'name': 'oxford street',
            'type': 'road',
            'price': 300,
            'rent': 26,
            'rent_with_color_set': 52,
            'rent_with_1_houses_0_hotels': 130,
            'rent_with_2_houses_0_hotels': 390,
            'rent_with_3_houses_0_hotels': 900,
            'rent_with_4_houses_0_hotels': 1100,
            'rent_with_4_houses_1_hotels': 1275,
            'mortgage_value': 150,
            'unmortgage_value': 165,
            'houses_cost': 200,
            'hotels_cost': 200,
            'color': 'green',
            'board_num': 32,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'bond street': {
            'name': 'bond street',
            'type': 'road',
            'price': 320,
            'rent': 28,
            'rent_with_color_set': 56,
            'rent_with_1_houses_0_hotels': 150,
            'rent_with_2_houses_0_hotels': 450,
            'rent_with_3_houses_0_hotels': 1000,
            'rent_with_4_houses_0_hotels': 1200,
            'rent_with_4_houses_1_hotels': 1400,
            'mortgage_value': 160,
            'unmortgage_value': 176,
            'houses_cost': 200,
            'hotels_cost': 200,
            'color': 'green',
            'board_num': 34,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'park lane': {
            'name': 'park lane',
            'type': 'road',
            'price': 350,
            'rent': 35,
            'rent_with_color_set': 70,
            'rent_with_1_houses_0_hotels': 175,
            'rent_with_2_houses_0_hotels': 500,
            'rent_with_3_houses_0_hotels': 1100,
            'rent_with_4_houses_0_hotels': 1300,
            'rent_with_4_houses_1_hotels': 1500,
            'mortgage_value': 175,
            'unmortgage_value': 193,
            'houses_cost': 200,
            'hotels_cost': 200,
            'color': 'blue',
            'board_num': 37,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'mayfair': {
            'name': 'mayfair',
            'type': 'road',
            'price': 400,
            'rent': 50,
            'rent_with_color_set': 100,
            'rent_with_1_houses_0_hotels': 200,
            'rent_with_2_houses_0_hotels': 600,
            'rent_with_3_houses_0_hotels': 1400,
            'rent_with_4_houses_0_hotels': 1700,
            'rent_with_4_houses_1_hotels': 2000,
            'mortgage_value': 200,
            'unmortgage_value': 220,
            'houses_cost': 200,
            'hotels_cost': 200,
            'color': 'blue',
            'board_num': 39,
            'belongs_to': None,
            'is_mortgaged': False
        },
    }
    return dict_roads


def get_properties():

    dict_properties = {
        'kings cross station': {
            'name': 'kings cross station',
            'type': 'station',
            'price': 200,
            'rent': 25,
            'mortgage_value': 100,
            'unmortgage_value': 110,
            'board_num': 5,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'marylebone station': {
            'name': 'marylebone station',
            'type': 'station',
            'price': 200,
            'rent': 25,
            'mortgage_value': 100,
            'unmortgage_value': 110,
            'board_num': 15,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'Fenchurch st. station': {
            'name': 'Fenchurch st. station',
            'type': 'station',
            'price': 200,
            'rent': 25,
            'mortgage_value': 100,
            'unmortgage_value': 110,
            'board_num': 25,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'liverpool st station': {
            'name': 'liverpool st station',
            'type': 'station',
            'price': 200,
            'rent': 25,
            'mortgage_value': 100,
            'unmortgage_value': 110,
            'board_num': 35,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'Electric company': {
            'name': 'Electric company',
            'type': 'utility',
            'price': 150,
            'rent': None,  # utility's rent depends of dice value
            'mortgage_value': 75,
            'unmortgage_value': 83,
            'board_num': 12,
            'belongs_to': None,
            'is_mortgaged': False
        },
        'water works': {
            'name': 'water works',
            'type': 'utility',
            'price': 150,
            'rent': None,  # utility's rent depends of dice value
            'mortgage_value': 75,
            'unmortgage_value': 83,
            'board_num': 28,
            'belongs_to': None,
            'is_mortgaged': False
        }

    }
    return dict_properties


def get_color_to_house_mapping():

    dict_color_to_house_mapping = {'brown': ['old kent road', 'whitechapel road'],
                                   'light_blue': ['the angel islington', 'euston road', 'pentonville road'],
                                   'purple': ['pall mall', 'whitehall', 'northumberland avenue'],
                                   'orange': ['bow street', 'marlborough street', 'vine street'],
                                   'red': ['strand', 'fleet street', 'trafalgar square'],
                                   'yellow': ['leicester square', 'coventry street', 'piccadilly'],
                                   'green': ['regent street', 'oxford street', 'bond street'],
                                   'blue': ['park lane', 'mayfair']}

    return dict_color_to_house_mapping


def get_community_chest_cards():

    return {"stock_sale": "FROM SALE OF STOCK YOU GET 50.",
              "birthday": "IT'S YOUR BIRTHDAY. COLLECT 10 FROM EACH PLAYER.",
              "holiday_fund": "HOLIDAY FUNC MATURES. COLLECT 100",
              "hospital_fees": "HOSPITAL FEES. PAY 100.",
              "second_price": "YOU HAVE WON SECOND PRIZE IN A BEAUTY CONTEST. COLLECT 100",
              "school_fees": "SCHOOL FEES. PAY 50.",
              "jail": "GO TO JAIL. GO DIRECTLY TO JAIL. DO NOT PASS GO. DO NOT COLLECT 200.",
              "inherit": "YOU INHERIT 100.",
              "consultancy": "COLLECT 25 CONSULTANCY FEE.",
              "income_tax": "INCOME TAX REFUND. COLLECT 20.",
              "insurance": "LIFE INSURANCE MATURES. COLLECT 100.",
              "bank_error": "BANK ERROR IN YOUR FAVOUR. COLLECT 200.",
              "doctor_fees": "DOCTOR'S FEES. PAY 50.",
              "to_go": "ADVANCE TO GO. COLLECT 200.",
              "street_repair": "YOU ARE ASSESSED FOR STREET REPAIRS: PAY 40 PER HOUSE AND 115 PER "
                               "HOTEL YOU OWN.",
              "out_of_jail": "GET OUT OF JAIL FREE. THIS CARD MAY BE KEPT UNTIL NEEDED, TRADED "
                             "OR SOLD."}